--11.13_moning_quiz

SELECT * FROM TABLE_DATA_1;
SELECT * FROM TABLE_DATA_2;
SELECT * FROM TABLE_COLC;


CREATE TABLE TABLE_DATA_1
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_DATA_2
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_COLC
(
std_date DATE,
CHECK_DATA1 VARCHAR2(6),
CHECK_DATA2 VARCHAR2(6)
);

INSERT INTO TABLE_DATA_1 VALUES (1, '2023-04-01');
INSERT INTO TABLE_DATA_1 VALUES (2, '2023-04-02');
INSERT INTO TABLE_DATA_1 VALUES (3, '2023-04-03');
INSERT INTO TABLE_DATA_1 VALUES (4, '2023-04-04');

INSERT INTO TABLE_DATA_2 VALUES (1, '2023-04-02');
INSERT INTO TABLE_DATA_2 VALUES (2, '2023-04-03');
INSERT INTO TABLE_DATA_2 VALUES (3, '2023-04-04');
INSERT INTO TABLE_DATA_2 VALUES (4, '2023-04-05');
INSERT INTO TABLE_DATA_2 VALUES (5, '2023-04-06');



--A업체 병합쿼리

MERGE INTO TABLE_COLC c
USING TABLE_DATA_1 d1
ON (c.std_date = d1.create_date)
 WHEN MATCHED THEN -- 일치하면 업데이트
    UPDATE SET c.check_data1 ='Y'
WHEN NOT MATCHED THEN -- 일치하는게 없으면 추가 (인서트)
    INSERT VALUES (d1.create_date, 'Y', 'N');

    
--B업체 병합쿼리

MERGE INTO TABLE_COLC c
USING TABLE_DATA_2 d2
ON (c.std_date = d2.create_date)
 WHEN MATCHED THEN -- 일치하면 업데이트
    UPDATE SET c.check_data2 ='Y'
WHEN NOT MATCHED THEN -- 일치하는게 없으면 추가 (인서트)
    INSERT VALUES (d2.create_date, 'N', 'Y');



--병합처리 후 조회 결과

SELECT * FROM TABLE_DATA_1;
SELECT * FROM TABLE_DATA_2;
SELECT * FROM TABLE_COLC
ORDER BY STD_DATE;


DELETE TABLE_COLC;
